version: '3.8'

services:
  # YOUR SPRING BOOT APP CONTAINER
  app:
    build: .
    container_name: scheduler-app
    ports:
      - "8080:8080"
    restart: on-failure

    environment:
      - SPRING_PROFILES_ACTIVE=local
